# Generated by Django 5.2.5 on 2025-08-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300, unique=True)),
                ('link', models.URLField(unique=True)),
                ('published', models.DateField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('full_content', models.TextField()),
                ('tags', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['published'], name='feed_newsar_publish_f9fced_idx'), models.Index(fields=['source'], name='feed_newsar_source_cee4f7_idx')],
            },
        ),
    ]
