# Generated by Django 5.2.5 on 2025-08-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticlemodel',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='newsarticlemodel',
            name='tags',
        ),
    ]
